spring:
  application:
    name: query
  datasource:
    url: jdbc:mysql://192.168.10.86:3322/test1
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true